### ISSUE TITLE
Rust output incomplete - StateContext

### ISSUE THREAD

**Issue by bradnelson** [frame-lang/frame_transpiler#1]
I'm guessing this is already known as Rust support is incomplete, but I thought I'd drop an issue as it's one of the few remaining issues I'm seeing.  Presently, I can compile Rust output from Frame files that don't include heirarchical state machines, but if there's hierarchy they fail on *_state() functions that include this line in interface event handler code:

```
StateContext stateContext = null;
```

Error: `error: expected one of '!', '.', '::', ';', '?', '{', '}', or an operator, found 'stateContext'`

**Comment by frame-lang** [comment]
Can you share the code that shows the problem? The Rust code gen is definately not finished but I don't see that particular issue with the Hello World example: https://gist.github.com/frame-lang/0daf0338e4a92b755eb1464c7c5c137f

**Comment by bradnelson** [comment]
Looks like I mis-identified what caused the issue, hierarchy was just one difference but I guess not the key one.  Looks like it adds that StateContext code when there's a parameter passed to a state entry event.  This gist recreates the issue:

https://gist.github.com/bradnelson/a0bd0302e18e216b82231ed3ce36a590

**Comment by bradnelson** [comment]
I believe this has been fixed.  Thank you Mark!
