### ISSUE TITLE
System Parameters not handled message parameter

### ISSUE THREAD

**Issue by deepaksharmaongraph** [frame-lang/frame_transpiler#104]
I have found a bug in frame demos in system parameters. some code lines are missing. msg is not handled by code.

params := make(map[string]interface{})
params["msg"] = msg;

![image](https://user-images.githubusercontent.com/103118428/165968039-cce54b2d-2fb1-4c5a-a7be-be87cdaaa8f5.png)

**Comment by frame-lang** [comment]
Should be fixed now. Please close issue if so.

**Comment by deepaksharmaongraph** [comment]
I have tested in-branch v0.10.0. **Not working**
![image](https://user-images.githubusercontent.com/103118428/167349107-08e2a718-107a-4ba3-ad54-e3b6e90b7179.png)

**Comment by frame-lang** [comment]
Ok I generate this with the latest checkin. LMK if still not working:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/6098246/168430381-042e23f0-a523-46d9-8c94-e902bf40f6b6.png">
