### ISSUE TITLE
System parameters don't throw errors 

### ISSUE THREAD

**Issue by frame-lang** [frame-lang/frame_transpiler#107]
If a system parameter is specified but there isn't a matching parameter or variable the parser doesn't throw an error.

```
#SystemParams [msg:string]

-domain-

##
```

Should throw an error about missing domain variable.

**Comment by deepaksharmaongraph** [comment]
Issue is fixed now

**Comment by frame-lang** [comment]
Fixed in 789350fd8e8fa74d19d557bff4c29fb5791cf8c7
