### ISSUE TITLE
string literal not properly handled in golang

### ISSUE THREAD

**Issue by frame-lang** [frame-lang/frame_transpiler#115]
-domain-
    var tape:Log = \`vec![]\`

results in:

/Users/marktruluck/projects/frame_transpiler/target/debug/framec -l golang /Users/marktruluck/projects/frame-demos/go/v0.10.0_tests/scratch2.frm
TODO: visit_literal_expression_node_to_string

Process finished with exit code 0

**Comment by deepaksharmaongraph** [comment]
It is handled
