### ISSUE TITLE
Add file name of source Frame spec to MachineInfo

### ISSUE THREAD

**Issue by walkie** [frame-lang/frame_transpiler#76]
We have a scenario where we need to know the file name of the Frame spec that generated a particular state machine. This can easily be added to the MachineInfo struct available via the runtime system (in the Rust backend).

It'd be easy to store the whole source file path there, but that might encourage some hacky/non-portable uses, so not sure whether that's a good idea... Maybe it's OK to provide it as long as it's just documented accordingly?

**Comment by walkie** [comment]
I'll plan to add at least the file name when I get back from vacation. Should be quick and easy.

**Comment by frame-lang** [comment]
First off I encourage you to experiment with the Rust implementation as long as the options are configurable, which is what I understand you are doing.

Second - would it make sense to keep the canonical name in a repo as the path?  Go's module management system works like that (I'm learning about it now) and it seems pretty elegant. Also has semantic versioning (which I don't understand yet). And perhaps a hash of the file for validation. 

Have a great vacation!

**Comment by walkie** [comment]
Done in #82. I added the file path as seen by Framec and a SHA-256 hash of the contents (good idea!) to the `MachineInfo` type accessible via the Rust runtime system. The new info will be included whenever the runtime system is enabled for the Rust backend.
