### ISSUE TITLE
syntax error for python when apply conditional statement for number.

### ISSUE THREAD

**Issue by gaurav-ongraph** [frame-lang/frame_transpiler#99]
![Screenshot from 2022-04-11 13-46-08](https://user-images.githubusercontent.com/69450887/162740458-b1b86232-c551-4cea-981e-ff25629cd5ff.png)

Solution: 
We can resolve it by changing ") {"to ":" at line number 1901 and "else {" to "else:" at line number 1955 in python_visitor.rs

**Comment by deepaksharmaongraph** [comment]
It has been fixed
